name: nanodust
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - astropy=5.3.3
  - cdflib=1.2.0
  - certifi=2023.7.22
  - ipykernel=6.25.0
  - ipython=8.15.0
  - numpy-base=1.24.3
  - pandas=2.1.1
  - pickleshare=0.7.5
  - pip=23.2.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyreadr=0.4.7
  - pyrsistent=0.18.0
  - python=3.9.18
  - qt-main=5.15.2
  - requests=2.31.0
  - scikit-image=0.19.3
  - scipy=1.11.3
  - snakemake-minimal=7.22.0
  - spyder=5.4.3
  - unidecode=1.2.0
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - watchdog=2.1.6
  - xarray=2023.6.0
  - pip:
      - fonttools==4.39.3
      - numpy==1.24.2
      - orbitalpy==0.7.0
      - represent==1.6.0.post0
      - sgp4==2.22
      - spacepy==0.4.1
      - sunpy==4.1.5
      - sunpy-soar==1.6.2
