name: nanodust
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiofiles=22.1.0
  - aioftp=0.21.4
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - amply=0.1.6
  - aom=3.6.0
  - appdirs=1.4.4
  - arrow=1.2.3
  - arrow-cpp=11.0.0
  - asciitree=0.3.3
  - asdf=2.15.1
  - asdf-astropy=0.4.0
  - asdf-coordinates-schemas=0.2.0
  - asdf-standard=1.0.3
  - asdf-transform-schemas=0.3.0
  - asdf-unit-schemas=0.1.0
  - astroid=2.14.2
  - astropy=5.3.3
  - astropy-healpix=0.7
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - atomicwrites=1.4.0
  - attrs=23.1.0
  - autopep8=1.6.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.3.0
  - blas=1.0
  - bleach=6.0.0
  - blosc=1.21.3
  - bokeh=3.2.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cdflib=1.2.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - configargparse=1.4
  - connection_pool=0.0.3
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=41.0.3
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.6.0
  - dask-core=2023.6.0
  - datrie=0.8.2
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.7
  - distributed=2023.6.0
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - dpath=2.1.5
  - drms=0.6.3
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - fasteners=0.17.3
  - fftw=3.3.9
  - filelock=3.9.0
  - flake8=6.0.0
  - flit-core=3.9.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.9.2
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.30
  - glib=2.69.1
  - glog=0.5.0
  - glpk=4.65
  - glymur=0.12.5
  - greenlet=2.0.1
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - h5netcdf=1.2.0
  - h5py=3.7.0
  - hdf5=1.12.1
  - html5lib=1.1
  - humanfriendly=10.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2023.1.23
  - imagecodecs-lite=2019.12.3
  - imageio=2.26.0
  - imagesize=1.4.1
  - importlib-metadata=6.0.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - isodate=0.6.1
  - isort=5.9.3
  - jaraco.classes=3.2.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jellyfish=1.0.1
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - jpeg=9e
  - jplephem=2.19
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_pygments=0.1.2
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.1.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=4.9.3
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - mpl_animators=1.1.0
  - mpmath=1.3.0
  - msgpack-python=1.0.6
  - multidict=6.0.2
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - numcodecs=0.11.0
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - numpydoc=1.5.0
  - openjpeg=2.4.0
  - openssl=3.1.3
  - orc=1.7.4
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parfive=2.0.2
  - parso=0.8.3
  - partd=1.4.0
  - pathspec=0.10.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - plac=1.3.4
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - poyo=0.5.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pyarrow=11.0.0
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyerfa=2.0.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtwebengine=5.15.7
  - pyreadr=0.4.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytoolconfig=1.2.5
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - re2=2022.04.01
  - reproject=0.12.0
  - requests=2.31.0
  - requests-file=1.5.1
  - requests-toolbelt=1.0.0
  - reretry=0.11.8
  - rope=1.7.0
  - rtree=1.0.1
  - scikit-image=0.19.3
  - scipy=1.11.3
  - semantic_version=2.8.5
  - setuptools=68.2.2
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snakemake-minimal=7.22.0
  - snappy=1.1.9
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - spyder-kernels=2.4.4
  - sqlalchemy=2.0.21
  - sqlite=3.41.2
  - stack_data=0.2.0
  - stopit=1.1.2
  - tabulate=0.8.10
  - tbb=2021.8.0
  - tblib=2.0.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - throttler=1.2.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - toposort=1.10
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ujson=5.4.0
  - unicodedata2=15.0.0
  - unidecode=1.2.0
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.14.1
  - xarray=2023.6.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.7.0
  - xz=5.4.2
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.8.1
  - yte=1.5.1
  - zarr=2.16.1
  - zeep=4.1.0
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - fonttools==4.39.3
      - numpy==1.24.2
      - orbitalpy==0.7.0
      - represent==1.6.0.post0
      - sgp4==2.22
      - spacepy==0.4.1
      - sunpy==4.1.5
      - sunpy-soar==1.6.2
