cdf_stat_location = "..\\data\\solo\\rpw\\tds_stat\\"
cdf_tswf_e_location = "C..\\data\\solo\\rpw\\tds_wf_e\\"
cdf_mamp_location = "..\\data\\solo\\rpw\\mamp\\"
lo_f_cat_location = "..\\data\\solo\\rpw\\Amplitude data\\Index-Label-MaxAmplitude\\"
lo_f_cat_new_location = "..\\data\\solo\\rpw\\Amplitude data\\low_frequency_new\\Label-MaxAmplitude\\"
hi_f_cat_location = "..\\data\\solo\\rpw\\Amplitude data\\nanodust_classification\\all_events\\"
solo_ephemeris_file = "..\\data\\ephemerides\\solo_fine_ephemeris_noheader.txt"
venus_ephemeris_file = "..\\data\\ephemerides\\venus_fine_ephemeris_noheader.txt"